import Navbar from './components/Navbar'
import './styles/globals.css'

export const metadata = {
  title: 'CB-Progress',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
